apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  strategy: {}
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: devanilops/result-project:2.0
        name: server-project
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: servers-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources: {}

