apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: devanilops/server-project:2.0
        name: server-project
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: servers-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources: {}
        #server için 3 değişken servers-configten alındı, 1 değer de mysql-secretin sadece key değeri alınarak yapıldı.

